### Gets Fallback message
GET {{baseUri}}/
Accept: */*

### Create new object
POST {{baseUri}}/
Accept: application/json
Content-Type: application/json

{
  "name": "test",
  "description": "test",
  "price": 10.0,
  "currency": "EUR"
}

### Upsert object
PUT {{baseUri}}/a-static-id
Accept: application/json
Content-Type: application/json

{
  "name": "test-upsert",
  "description": "upserted object",
  "price": 10.0,
  "currency": "EUR"
}

### Gets objects (and store ID)
GET {{baseUri}}/
Accept: application/json,text/html

> {%
   response.body.forEach(item => {
     client.global.set("id", item.id)
   })
 %}

### Delete object by id
DELETE {{baseUri}}/{{id}}
