### Gets Fallback message
GET {{baseUri}}/
Accept: */*

### Gets objects
GET {{baseUri}}/
Accept: application/json,text/html

### Create new object
POST {{baseUri}}/
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "description": "test",
    "price": 10.0,
    "currency": "EUR"
}
